name: synnet
channels:
  - pytorch
  # - dglteam # only needed for gin
  - conda-forge
dependencies:
  - python=3.9.*
  - pytorch::torchvision
  - pytorch::pytorch=1.9.*
  - pytorch-lightning
  - rdkit=2022.03.*
  - datamol
  - pytdc
  - scikit-learn>=1.1.*
  - numba
  - ipykernel
  - nb_conda_kernels
  - black=22.6.*
  - black-jupyter=22.6.*
  - isort=5.10.*
  - pip
  - pip:
    - setuptools==59.5.0 # https://github.com/pytorch/pytorch/issues/69894
#    - dgllife # only needed for gin, will force scikit-learn < 1.0
    - pathos
    - rich
    - pyyaml
    - fcd_torch # for evaluators in pytdc
    - wandb
