name: null # as displayed in wandb.ai
project: "synnet" # as displayed in wandb.ai
description: "default config"
group: "rt1"
result_dir: "tmp/rt1"
data:
  Xtrain_file: "data/featurized/Xy/X_rt1_train.npz"
  ytrain_file: "data/featurized/Xy/y_rt1_train.npz"
  Xvalid_file: "data/featurized/Xy/X_rt1_valid.npz"
  yvalid_file: "data/featurized/Xy/y_rt1_valid.npz"
  aug-fraction: 0.0
parameters:
  task: regression
  batch_size: 128
  input_dim: 12288 # 3*4096
  output_dim: 256
  hidden_dim: 3800
  num_layers: 4
  num_dropout_layers: 1
  dropout: 0.4
  optimizer: adam
  learning_rate: 0.00003
  max_epochs: 601
  loss: cosine_distance
  valid_loss: cosine_distance
  val_freq: 10 # epoch
