name: null # as displayed in wandb.ai
project: "synnet" # as displayed in wandb.ai
description: "default config"
group: "rt2"
result_dir: "tmp/rt2"
data:
  Xtrain_file: "data/featurized/Xy/X_rt2_train.npz"
  ytrain_file: "data/featurized/Xy/y_rt2_train.npz"
  Xvalid_file: "data/featurized/Xy/X_rt2_valid.npz"
  yvalid_file: "data/featurized/Xy/y_rt2_valid.npz"
  aug-fraction: null
parameters:
  task: regression
  batch_size: 64
  input_dim: 16475 # 4*4096 + 91
  output_dim: 256
  hidden_dim: 3000
  num_layers: 5
  num_dropout_layers: 1
  dropout: 0.5
  optimizer: adam
  learning_rate: 0.00003
  max_epochs: 601
  loss: mse
  valid_loss: mse
  val_freq: 10 # epoch
